indie_pop_artist_song = [
"Bahamas - All I've Ever Known",
"Peach Pit - Tommy's Party",
"Summer Salt - One Last Time",
"HONNE - Someone That Loves You",
"LANY - Thick And Thin",
"HONNE - Day 1 ◑",
"HONNE - It Ain't Wrong Loving You",
"LANY - Hurts",
"HONNE - 3am",
"HONNE - Warm on a Cold Night",
"LANY - ILYSB (STRIPPED)",
"LANY - 13",
"HONNE - Woman",
"LANY - Malibu Nights",
"HONNE - free love (dream edit)",
"Anson Seabra - Hindenburg Lover",
"HONNE - la la la that’s how it goes (dream edit)",
"LANY - nobody else",
"92914 - Starlight",
"HONNE - gone gone gone (dream edit)",
"Pink Sweat$ - Lows",
"Before You Exit - Same Sun",
"Anson Seabra - Trying My Best",
"Anson Seabra - That’s Us",
"Rhye - The Fall (live)",
"HONNE - no song without you (london session)",
"Anson Seabra - Emerald Eyes",
"Daniel Caesar - Blessed",
"Cigarettes After Sex - You're the Only Good Thing In My Life",
"Bruno Major - Easily",
"Bruno Major - Regent’s Park",
"Softy - Candle lit dinner",
"Alt Bloom - October Eyes",
"Omar Apollo - Brakelights",
"McClenney - Just Stay",
"Benny Sings - Realize",
"Jesse Levine - What Happened",
"Corinne Bailey Rae - Put Your Records On",
"Scoop X On Planets - Too",
"Eloise - Subside",
"Kings of Convenience - Misread (Acoustic Session)",
"Feng Suave - Venus Flytrap",
"HONNE - It Ain't Wrong Loving You",
"Sunset Rollercoaster - My Jinji",
"Joji - Rain On Me",
"Phora - Holding On",
"JC Stewart - The Wrong Ones",
"Rhye - The fall",
"Cigarettes After Sex - Truly",
"Cigarettes After Sex - Sweet",
"Rhye - Open",
"Rhye - Song for you",
"igarettes After Sex - K.",
"Cigarettes After Sex - Apocalypse",
"Rhye - Wicked dreams",
"Rhye - Beautiful",
"Rhye - Please",
"Cigarettes After Sex - Nothing’s gonna hurt you baby",
"Cigarettes After Sex - Affection",
"Cigarettes After Sex - Crush",
"Rhye - Stay safe",
"Bonobo, Rhye - Break apart",
"LANY - cowboy in LA",
"No Rome - Narcissist (ft.The 1975)",
"Phoenix - Fior Di Latte",
"Sasha Sloan - Is It Just Me?",
"Troye Sivan - Strawberries & Cigarettes",
"Conan Gray - Wish You Were Sober",
"LANY - Super Far",
"Shoffy - Cool Again",
"BETWEEN FRIENDS - iloveyou",
"Alexander 23 - Mars",
"SG Lewis, Clairo - Throwaway",
"Lauv - Love Somebody",
"ROLE MODEL - say it first",
"LANY - anything 4 u",
"Daniel Caesar - Death & Taxes",
"Daniel Caesar - Get You (feat. Kali Uchis)",
"Daniel Caesar - Best Part (feat. H.E.R.)",
"FKJ, Tom Misch - Losing my way",
"Tom Misch - It runs through me",
"Tom Misch - South of the river",
"FKJ, Masego - Tadow",
"FKJ - Die with a smile",
"Tom Misch - Lost in Paris",
"FKJ - We ain’t feeling time",
"Tom Misch - Disco yes",
"Tom Misch - Watch me dance",
"FKJ - Ylang Ylang",
"Jorja Smith - Teenage Fantasy",
"Jorja Smith - Blue Lights",
"Joji - Sanctuary",
"Pink Sweats - At My Worst",
"Khalid - Talk",
"Lauv - Never not",
"Khalid- Location",
"Ruel - Painkiller",
"Khalid - Better",
"Troye Sivan - youth",
"MAX - Checklist (feat. Chromeo)",
"Niall Horan - Nice To Meet Ya",
"Dua Lipa - Don't Start Now",
"Liam Payne - Stack It Up (feat. A Boogie Wit Da Hoodie)",
"Raye - Love Me Again",
"KIDDO - Dead Alive",
"Kav Verhouzer - Get What You Came For (feat. BullySongs)",
"Embody - Be Cool (feat. Bailey, Marco Foster)",
"Galantis - Satisfied (feat. MAX)",
"Ofenbach - Paradise (feat. Benjamin Ingrosso)",
"Chromeo - Just Friends (feat. Amber Mark)",
"Seeb - Fade Out",
"Guy Sebastian - Choir",
"Faustix - Lose Myself",
"Bishop Briggs - CHAMPION",
"Charli XCX - Blame It On Your Love (feat. Lizzo)",
"Basic Tape - So Good",
"Jax Jones - You Don't Know Me (feat. Raye)",
"HRVY - Million Ways",
"Foley - Cola",
"Samuel Daayata - Throw Popcorn (feat. Isac Elliot)",
"Against The Current - Voices",
"Alex Alexander - Body on Me",
"Men I Trust - Lauren",
"Family of the Year - Hero",
"Yung Bae - Revolving",
"Mac Miller - Dang! (feat. Anderson .Paak)",
"Gallant - Weight in Gold",
"Anderson .Paak - Make It Better (feat. Smokey Robinson)",
"Peggy Gou - Starry Night",
"Mullally - Sweet Coffee (feat. Bassette)",
"Easy life - Dead Celebrities",
"BENEE - Glitter",
"Mae Muller - Therapist",
"Conan Gray - Generation Why",
"Heaven Falls - Fall on me",
"Inhaler - Ice Cream Sundae"]

indie_pop_song_artist = [
"SLOW DANCING IN THE DARK - Joji",
"YKWIM? - Yot Club",
"In My Head - Bedroom",
"With Love - HARBOUR",
"You're Somebody Else - Flora Cash",
"I Can't Handle Change - Roar",
"i was all over her - Salvia Path",
"As the World Caves In - Matt Maltese",
"Daddy Issues - The Neighbourhood",
"Hey Kids - Molina",
"Pope is a Rockstar - SALES",
"Televisions - Current Joys",
"Always forever - Cults",
"505 - Arctic Monkeys"]

print(len(indie_pop_artist_song) + len(indie_pop_song_artist))
for music in indie_pop_artist_song:
    artist, song = music.split("-")
    # song, artist = music.split("-")
    title = song
    artist = artist
    # print("{")
    # print('    "artist": "{}",'.format(str(artist[:-1])))
    # print('    "title": "{}"'.format(str(title[1:])))
    # print("},")