music_list_classic = [
"Beethoven, Symphony 5, movement I",
"Tchaikovsky, 1812 overture",
"Beethoven, Symphony 9, movement IV(Ode to Joy)",
"Bach, Toccata and Fugue in D minor",
"Orff, Carmina Burana – O Fortuna",
"Strauss, Blue Danube Waltz",
"Verdi, Requiem – Dies Irae",
"Mozart, Requiem – Dies Irae",
"Offenbach, Orpheus in the Underworld – Infernal Galop",
"Beethoven, 7.th Symphony – movement II",
"Strauss, Also Sprach Zarathustra",
"Bizet, Carmen – Chanson de Toreador",
"Ravel, Bolero",
"Grieg, Peer Gynt – In the hall of mountain king",
"Wagner, Ring des Nibelungen – Ride of the Valkyries",
"Prokofiev, Romeo and Juliet – Montagues and Capulets",
"Brahms, Hungarian Dance no.5",
"Gershwin, Rhapsody in Blue",
"Beethoven, Symphony 5, movement III",
"Mozart, Requiem – Lacrimosa",
"Strauss Senior, Radetzky March",
"Khachaturian, Masquerade Waltz",
"Smetana, Ma Vlast – Moldau River",
"Dvorak, Symphony 9, movement IV",
"Chopin, Revolutionary Etude",
"Mahler, Symphony 5",
"Mozart, Requiem – Requiem Aeternam",
"Vivaldi, Four Seasons – Winter",
"Rosas, Over the Waves",
"Mussorgski, Night on the Bald Mountain",
"Mozart, Symphony 40",
"Holst, The Planets – Mars, Bringer of War",
"Beethoven, Symphony 9, movement II",
"Chopin, Fantasie Improptu",
"Tchaikovsky, Marche Slave",
"Verdi, Aida – Triumphal March",
"Shostakovich, Second Waltz",
"Grieg, Peer Gynt – Death of Aase",
"Mozart, Symphony 25",
"Pergolesi, Stabat Mater Dolorosa",
"Verdi, Nabucco – Va Pensiero(Chorus of the Hebrew Slaves)",
"Kchachaturian, Sabre Dance",
"Dvorak, Slavonic Dance 8",
"Fucik, Entry of the Gladiators",
"Beethoven, Moonlight Sonata",
"Rossini, William Tell Overture",
"Grieg, Piano Concerto",
"Tchaikovsky, Piano Concerto I",
"Grieg, Peer Gynt – Morning Mood",
"Tchaikovsky, Waltz of the Flowers",
"Strauss, Wiener Blut",
"Bizet, Carmen – Les Toreadors",
"Vivaldi, Four Seasons – Spring",
"Dvorak, Slavonic Dance 1",
"Strauss, Tritsch-Tratsch Polka",
"Strauss, Voices of Spring",
"Verdi, La traviata – Drinking Song",
"Tchaikovsky, Swan Lake Waltz",
"Prokofiev, Alexander Nevsky – Crusaders in Pskov",
"Liszt, Hungarian Rhapsody 2",
"Verdi, Il Trovatore – Anvil Chorus",
"Grieg, Peer Gynt – Anitra’s Dance",
"Prokofiev, Peter and Wolf – The Story Begins",
"Mendellsohn, Symphony movement I",
"Strauss, Tales from the Vienna Woods",
"Rachmaninov, Prelude in C sharp Minor",
"Barber, Adagio for Strings",
"Rossini, Barber of Seville – Al Factotum",
"Brahms, Hungarian dance 6",
"Ivanovic, Waves of Danube",
"Waldteufel, Skater’s Waltz",
"Mozart, Don Giovanni Overture",
"Puccini, Turandot – Nessun Dorma",
"Bizet, Carmen – Habanera",
"Chopin, Waltz op.64",
"Milhaud, Le Boeuf Sur le Toit",
"Jenkins, Palladio",
"Gustav Holst, The Planets – Jupiter, Bringer of Jolity",
"Beethoven, 3.rd Symphony",
"Handel, Hallelujjah Chorus",
"Saint Saens, Carnival of the Animals – Finale",
"Sibelius, Finlandia",
"Eugen Doga, Gramofon",
"Beethoven, Egmont Overture",
"Tchaikovsky, Nutcracker – March",
"Rimsky-Korsakoff, Flight of the Bumblebee",
"Monti, Czardas",
"Saint Saens, Carnival of the Animals – Aquarium",
"Leontovich, Carol of the Bells",
"Strauss, Egyptian March",
"Chopin, Funeral March",
"Haydn, Trumpet Concerto",
"Tchaikovsky, The Nutcracker – Russian Dance",
"Eugen Doga, My Sweet and Tender Beast",
"Rossini, Barber of Seville – Overture",
"Sousa, Stars and Stripes Forever",
"Strauss, Russian March",
"Mozart, Eine Kleine Nachtmusik",
"Bach, Cello Suite",
"Elgar, Pomp and Circumstance March",
"Tchaikovsky, Romeo and Juliet Fantasy Overture",
"Bizet, Carmen, Gypsy Dance",
"Wagner, Lohengrin – Prelude To Act 3",
"Bach, Mass in B minor",
"Mozart, Rondo alla Turca",
"Mozart, Marriage of Figaro – Overture",
"Beethoven, Ruins of Athens – Turkish March",
"Mussorgsky, Pictures At An Exhibition – Promenade",
"Wagner, Tristan and Isolde",
"Beethoven, String Quartet in C sharp minor",
"Bach, St. Matthew Passion",
"Bach, Air on the G String",
"Verdi, Rigoletto – La Donna È Mobile",
"Beethoven, Missa Solemnis",
"Handel, Alla Hornpipe",
"Stravinsky, The Rite of Spring",
"Rachmaninov, Rhapsody On A Theme Of Paganini, 18th Variation",
"Strauss, Persian March",
"Vivaldi, Four Seasons – Summer",
"Tchaikovsky, Sleeping Beauty – Garland Waltz",
"Sibelius, Karelia Suite – Alla Marcia",
"Debussy, Suite Bergamasque: Clair De Lune",
"Saint-Saens, Danse Macabre",
"Ricketts, Colonel Bogey March",
"Schubert, Ave Maria",
"Bach, Badinerie",
"Strauss, Tritsch Tratsch Polka",
"Mendellsohn, Midsummer Night’s Dream – Wedding March",
"Tchaikovsky, Symphony 6",
"Smetana, Bartered Bride – Dance Of The Comedians",
"Handel, Sarabande",
"Tchaikovsky, Nutcracker – Dance Of The Mirlitons",
"Copland, Fanfare for the Common Man",
"Sousa, Liberty Bell",
"Delibes, Sylvia – Pizzicato",
"Tchaikovsky, Nutcracker – Dance Of The Sugar-Plum Fairy",
"Tchaikovsky, Swan Lake – Dance Of The Little Swans",
"Offenbach, Tales Of Hoffmann – Barcarolle",
"Bach, Bourrée In E Minor",
"Mendellsohn, Spring Song",
"Delibes,Lakmé – Flower Duet",
"Dvorak, Humoresque No. 7",
"Mozart, Marriage Of Figaro – Wedding March",
"Beethoven, Appasionata Sonate",
"Ponchielli, La Gioconda – Dance of the Hours",
"Smetana, Ma Vlast – Vysehrad",
"Handel, Solomon – Arrival Of The Queen Of Sheba",
"Adams, Nearer My God to Thee",
"Bach, Well Tempered Clavier",
"Mendellsohn, Hebrides Overture",
"Strauss, Emperor Waltz",
"Dvorak, Carnival Overture",
"Sibelius, Karelia Suite: Intermezzo",
"Schubert, Marche Militaire No. 1 (Military March)",
"Chopin, Nocturne Op. 9 No. 2",
"Handel, Ombra mai Fu",
"Kabalevsky, Comedians’ Galop",
"Borodin, Prince Igor – Polovtsian Dance No. 17 – Dance Of The Men",
"Chopin, Minute Waltz",
"Beethoven, Symphony 6",
"Strauss, Die Fledermaus Waltz",
"Tchaikovsky, Nutcracker – Pas De Deux",
"Tchaikovsky, Nutcracker – Overture",
"Handel, Zadok The Priest",
"Ketelbey, In a Persian Market",
"Beethoven, Fur Elise",
"Chopin, Etude Op. 10 No. 3",
"Respighi, Pines Of Rome – Pines Of The Appian Way",
"Purcell, Funeral Of Queen Mary",
"Albinoni, Adagio In G Minor",
"Mascagni, Cavalleria Rusticana – Intermezzo",
"Chopin, Heroic Polonaise",
"Stravinsky, Firebird Suite: Finale",
"Saint Saens, Symphony No. 3 (Organ) – Movement II",
"Vaughan Williams, Fantasia On Greensleeves",
"Bach, Cantata 1– Jesu, Joy Of Man’s Desiring",
"Handel, La Réjouissance",
"Sousa, Semper Fidelis",
"Peter, Circus Renz",
"Elgar, Enigma Variation No. 9",
"Mouret, Rondeau",
"Telemann, Tafelmusik – Quartet In G Major: I",
"Bach, Brandenburg Concerto 5",
"Mozart, Marriage Of Figaro – Sull’aria",
"Paganini, Caprice No. 24",
"Gounod, Funeral March of Marionette",
"Puccini, Madama Butterfly",
"Mozart, Clarinet Concerto II",
"Strauss, Till Eulenspiegel",
"Mozart, Queen of the Night Aria",
"Denza, Funiculi, Funicula",
"Chopin, Waltz op.6"
]
two_songs = []

for music in music_list_classic:
    composer, *song = music.split(",")
    if len(song) > 1:
        two_songs.append(music)
    else:
        pass
        # title = song[0]
        # print("{")
        # print('    "composer": "{}",'.format(str(composer)))
        # print('    "title": "{}"'.format(str(title)))
        # print("},")

for music in two_songs:
    composer, *song = music.split(",")
    for fragment in song:
        title = song[0] + "," + song[1]
    print("{")
    print('    "composer": "{}",'.format(str(composer)))
    print('    "title": "{}"'.format(str(title)))
    print("},")
