popular_kpop_song_artist = [
"벌써 12시 - CHUNG HA",
"너 그리고 나(NAVILLRERA) - GFRIEND",
"비밀이야 - WJSN",
"니가 하면 - GOT7",
"FANCY - TWICE",
"한숨 - LeeHi",
"VIew - SHINee",
"Good Luck - BEAST",
"Run - Epik High",
"MOVE - TAEMIN",
"Mr.Mr. - Girls' Generation",
"일곱 번째 감각 - NCT U",
"아 왜(I wait) - DAY6",
"I NEED U - BTS",
"공허해 - WINNER",
"THIS IS LOVE - SUPER JUNIOR",
"춤 - offonoff",
"나혼자 - SISTAR",
"눈, 코, 입 - TAEYANG",
"I Feel You	- Wonder Girls",
"CLOSER	- OH MY GIRL",
"이게 무슨 일이야 - B1A4",
"I Love You - 2NE1",
"스물셋 - IU",
"FANTASTIC BABY - BIGBANG",
"200% - AKMU",
"라비앙로즈 - IZ*ONE",
"All I Wannd DO - Jay Park",
"삐딱하게 - G_DRAGON",
"bonnie & clyde - DEAN",
"I - TAEYEON",
"Free Somebody - LUNA",
"Pandora - KARA",
"도원경(桃源鏡) - VIXX",
"너는 나 나는 너 - ZICO",
"기대해 - GIRL'S DAY",
"미쳐 - 4minute",
"널 너무 모르고 - Heize",
"으르렁 - EXO",
"좋겠어(I wish) - FTISLAND",
"위아래 - EXID",
"LUCIFER - SHINee",
"Shampoo - After School",
"왜(Keep Your Head Down) - TVXQ",
"Bubble Pop! - HyunA",
"너 같은 - DAL★Shabet",
"BAE BAE - BIGBANG",
"짧은 치마 - AOA",
"HER - Block B",
"봄날 - BTS",
"하.니.뿐. - 2PM",
"빛나리 - PENTAGON",
"팔레트 - IU",
"첫 사랑니(Rum Pum Pmu Pum) - f(x)",
"넌 is 뭔들 - MAMAMOO",
"Bad Girl Good Girl - miss A",
"사랑을 했다 - iKON",
"주인공 - SUNMI",
"Bad Boy - Red Velvet",
"휘파람 - BLACKPINK",
"Roly Poly - T_ARA",
"Touch My Body - SISTAR",
"에너제틱 - Wanna One",
"Sixth Sense - Brown Eyed Girls",
"양화대교 - Zion.T",
"TT - TWICE",
"STEP - KARA",
"아주 NICE - SEVENTEEN",
"Awoo - Lim Kim",
"Be My Baby - Wonder Girls",
"CALL ME BABY - EXO",
"Don't Be Shy(아끼지마) - Primary",
"4 Walls - f(x)",
"Bad Boy - BIGBANG",
"피 땀 눈물 - BTS",
"Sherlock.셜록(Clue+Note) - SHINee",
"I Got A Boy - Girls' Generation",
"내가 제일 잘 나가 - 2NE1",
"추격자 - INFINITE",
"빨간 맛 - Red Velvet",
"좋은 날 - IU",
"LOCO - ITZY",
"PING PONG - HyunA & E'DAWN",
"You can't sit with us - SUNMI",
"DUMB DUMB - SOMI",
"PTT (Paint the Town) - LOONA",
"색안경 (STEREOTYPE) - STAYC",
"ASAP - STAYC",
"Dun Dun Dance - OH MY GIRL",
"Next Level - aespa",
"I'm Not Cool - HyunA",
"On the Ground - ROSÉ",
"Weekend - TAEYEON",
"WE GO - fromis_9",
"Queendom - Red Velvet",
"The Feels - TWICE",
"Highway To Heaven - NCT 127",
"북극성 (Polaris) - NU'EST W",
"HOW R U TODAY - N.Flying",
"데리러가 (Good Evening) - SHINee",
"WAVE - ATEEZ",
"오솔레미오 (O Sole Mio) - SF9",
"우리의 새벽은 낮보다 뜨겁다 - SEVENTEEN",
"Never Ever - GOT7",
"Dejavu - NU'EST W",
"Answer - ATEEZE",
"Tag Tag Tag - VERIVERY",
"예뻤어 - DAY6",
"Shoot Out - MONSTA X",
"No Air - THE BOYZ",
"Welcome To My Playground - NCT 127",
"접근금지 (Prod. By 기리보이) - PENTAGON",
"쉽게 쓰여진 노래 (A Song Written Easily) - ONEUS",
"Trigger The Fever - NCT DREAM",
"D.D.D - THE BOYZ"]

popular_kpop_artist_song = [
"EXO - Power",
"EXO - LOVE ME RIGHT",
"EXO - 부메랑(Boomerang)",
"BAEKHYUN - Candy(캔디)",
"NCT DREAM - BOOM",
"NCT 127 - 영웅(英雄; Kick It)",
"NCT U - 90's Love",
"NCT DREAM - We Go Up",
"SUPER JUNIOR - Devil",
"SUPER JUNIOR - Hous Party",
"SUPER JUNIOR - Miracle",
"SUPER JUNIOR D&E - 1+1=LOVE",
"SEVENTEEN - 예쁘다",
"SEVENTEEN - HIT",
"INFINITE - 내꺼하자",
"TVXQ - 풍선(Ballons)",
"WINNER - ISLAND",
"WINNER - AH YEAH(아예)",
"ONF - Complete(널 만난 순간)",
"TXT - 9와 4분의 3 승장장에서 너를 기다려(Run Away)",
"DAY6 - 한 페이지가 될 수 있게",
"THE BOYZ - Whiplash",
"N.Flying - 안 진짜요(Oh really.)",
"Hightlight - 얼굴 찌푸리지 말아요",
"GOT7 - Lullaby",
"BTS - 작은 것들을 위한 시(Boy With Luv)(Feat. Halsey)",
"NU'EST - LOVE ME",
"ATEEZ - WAVE",
"BTOB - 신바람",
"GFRIEND - MAGO",
"BLACKPINK - Lovesick Girls",
"GFRIEND - Love Spell",
"Brave Girls - 치맛바람",
"LABOUM - 상상더하기",
"MAMAMOO - 딩가딩가",
"OH MY GIRL - 살짝 설렜어",
"TWICE - Alcohol_Free",
"Weekly - After School",
"Brave Girls - 운전만해",
"BIGBANG - Stupid Liar",
"BEAST - Beautiful",
"BIGBANG - 거짓말",
"B1A4 - SOLO DAY",
"iKON - 이별길",
"CNBLUE - 외톨이야",
"BTS - Save Me",
"Block B - Toy",
"HENRY - Trap",
"N.Flying - 옥탑방 (Rooftop)",
"ZE:A - 후유증",
"BEAST - 비가 오는 날엔",
"FTISLAND - 지독하게",
"Wanna One - Beautiful",
"BIGBANG - 붉은 노을",
"BTOB - 괜찮아요",
"CNBLUE - Love",
"WINNER - Love Me Love Me",
"BTOB - 그리워하다",
"TEENTOP - 긴 생머리 그녀"
]

popular_kpop_artist_song2 = [
"SF9 - Fall In Love",
"DAY6 - You make Me",
"Stray Kids - 미친 놈(Ex)",
"NU'EST W - Dejavu",
"ONF - 사랑하게 될 거야 (We Must Love)",
"PENTAGON - 밤에 비가 내리면",
"DAY6 - Love me or Leave me",
"SEVENTEEN - Ready to love",
"N.Flying - FLOWER FANTASY",
"AB6IX - 아직도 겨울 (A LONG WINTER)",
"PENTAGON - 봄눈",
"CRAVITY - 별",
"SF9 - 널 꽉 잡은 손만큼 (Like The Hands Tight)",
"NCT DREAM - 우리의 계절 (My Youth)",
"GOT7 - Take Me To You",
"Scenery of Riding Bicycle - 너에게 난 나에게 넌",
"Cool - All For You",
"Kim Hyung Joong - 그랬나봐",
"Kang Susie - 보라빛 향기",
"Toy - 좋은 사람(With 김형중)",
"SECHSKIES - 커플",
"SEVENTEEN - 어쩌나",
"THE BOYZ - bloom bloom",
"SHINee - view",
"NCT 127 - 메아리",
"NCT DREAM - My Page",
"DAY6 - Free하게",
"X1 - 웃을 때 제일 예뻐",
"CRAVITY - Cloud 9",
"TXT - 어느날 머리에서 뿔이 자랐다",
"VERIVERY - 불러줘",
"ASTRO - 숨바꼭질",
"Golden Child - Let Me",
"MXM - YA YA YA"]

popular_kpop_song_artist2 = [
"밤이 되니까 - PUNCH",
"주지마 - Loco & Hwasa",
"자니 - Primary",
"씨스루 - Primary",
"꺼내 먹어요 - Zion.T",
"사람 냄새 - GARY & JUNG_IN",
"바람이나 좀 쐐 - GARY",
"널 너무 모르고 - Heize",
"갖고 놀래 - BUMKEY",
"헤어지지 못하는 여자 떠나가지못하는 남자 - LeeSSang",
"? - Primary",
"그땐 그땐 그땐 - Supreme Team ",
"어떻게 생각해 - CHEEZE",
"네 생각 - John Park",
"광대 - LeeSSang",
"나빠 - Crush",
"거기서 거기 - Dynamic Duo",
"Hug Me - Crush",
"And July - Heize",
"오늘 취하면 - SURAN",
"하기나 해 - Gray",
"토요일의 끝에서 - Beenzino",
"시간을 달려서 (Rough) - GFRIEND",
"Destiny (나의 지구) - OH MY GIRL",
"그 시절 우리가 사랑했던 우리 (Beautiful Days) - LOVELYZ",
"STAY - BLACKPINK",
"너와 나 (Beautiful Time) - NCT DREAM",
"언젠가 우리의 밤도 지나가겠죠 - IZ*ONE",
"벚꽃이 지면 - I.O.I",
"피터팬 (Peter Pan) - EXO",
"365 - LOONA",
"방백 (Aside) - SHINee",
"첫눈에... (Snowy Wish) - GIRLS' GENERATION",
"달빛 소리 (Moonlight Melody) - Red Velvet",
"예뻤더라 (WE WERE) - WINNER",
"나의 모든 순간 (No Longer) - NCT 127",
"Square - Yerin Baek",
"No make Up - Zion.T",
"자니 - Primary",
"바람이나 좀 쐐 - GARY",
"광대 - LeeSSang",
"거기서거기 - Dynamic Duo",
"꺼내 먹어요 - Zion.T",
"씨스루 - Primary",
"갖고놀래 - BUMKEY",
"멋지게 인사하는 법 - Zion.T & Seulgi",
"잊어버리지마 - Crush",
"널 너무 모르고 - Heize",
"둘만의 세상으로 가 - Crush",
"죽일 놈- Dynamic Duo",
"헤어지지 못하는 여자 떠나가지 못하는 남자 - LeeSSang",
"그건 아마 우리의 잘못은 아닐거야 - Yerin Baek",
"어떻게 생각해 - CHEEZE",
"나빠 - Crush",
"그냥 - Zion.T",
"SOFA - Crush",
"Oasis - Crush",
"가끔 - Crush",
"She - Zion.T",
"그땐 그땐 그땐 - Supreme Team",
"출첵 - Dynamic Duo",
"잊을만하면 - Crush",
"And July - Heize",
"미안해 - Zion.T",
"저 별 - Heize",
"남아있어 - Loco",
"Bye Bye my Blue - Yerin Baek",
"어떻게 지내 - Crush",
"소녀 - Lee Moon Sae",
"네게 줄 수 있는건 오직 사랑뿐 - Byun Jin Sub",
"조조할인 - Lee Moon Sae, 이적",
"깊은 밤을 날아서 - Lee Moon Sae",
"널 사랑하겠어 - Zoo",
"숙녀에게 - Byun Jin Sub",
"그대 내 품에 - Yu Jae Ha",
"그대 떠나는 날에 비가 오는가 - Sanullim",
"슬픔 속에 그댈 지워야만 해 - Lee Hyun Woo",
"서로가 - Lee Moon Sae",
"사랑은 늘 도망가 - Lee Moon Sae",
"가로수 그늘 아래 서면 - Lee Moon Sae",
"사랑이라는 이유로 - Kim Kwang Seok",
"잊어야 한다는 마음으로 - Kim Kwang Seok",
"옛사랑 - Lee Moon Sae",
"칵테일 사랑 - Marronnier",
"하늘색 풍선 - god",
"비행기 - Turtles",
"붉은 노을 - Lee Moon Sae",
"아로하 - Cool",
"슬퍼지려 하기 전에 - Cool",
"일과 이분의 일 - Two Two",
"애상 - Cool",
"해변의 여인 - Cool"
]

print(len(popular_kpop_artist_song) + len(popular_kpop_song_artist) + len(popular_kpop_artist_song2) + len(popular_kpop_song_artist2))
for music in popular_kpop_artist_song:
    artist, song = music.split("-")
    # song, artist = music.split("-")
    title = song
    artist = artist
    print("{")
    print('    "artist": "{}",'.format(str(artist[:-1])))
    print('    "title": "{}"'.format(str(title[1:])))
    print("},")