indie_kpop_artist_song = [
"OOHYO - 청춘",
"Damons Year - Auburn",
"Damons Year - josee!",
"Damons Year - yours",
"SURL - 열기구",
"Nerd Connection - 좋은 밤 좋은 꿈",
"HYUKOH - Paul",
"Dasutt - Youth",
"Jannabi - 뜨거운 여름밤은 가고 남은 건 볼품없지만",
"Jannabi - She",
"The Black Skirts - EVERYTHING",
"Jang Beom June - 회상",
"Jannabi - 주저하는 연인들을 위해",
"Deli Spice - 고백",
"Car, the garden - 우리의 밤을 외워요",
"HYUKOH - LOVE YA!",
"Jannabi - 처음 만날때처럼",
"FROMM - 반딧불이",
"The Black Skirts - 나랑 아니면",
"Night Off - 잠",
"HYUKOH - TOMBOY",
"Jannabi - 꿈과 책과 힘과 벽",
"Yoon ji young - 언젠가 너와 나",
"The Black Skirts - 하와이 검은 모래",
"Jannabi - 나의 기쁨 나의 노래",
"Car, the garden - 꿈을 꿨어요",
"The Black Skirts - 난 아니에요",
"jungumul - blue",
"Car, the garden - 31",
"The Black Skirts - 혜야",
"Jannabi - 가을밤에 든 생각",
"The Black Skirts - SOMEDAY",
"SE SO NEON - 나는 새롭게 떠오른 외로움을 봐요",
"zunhozoon - After 10 Days",
"Juk Jae - 나랑 같이 걸을래",
"Car, the garden - 의연한 악수",
"zunhozoon - Message In A Bottle",
"Car, the garden - 명동콜링",
"J Rabbit - 내일을 묻는다",
"zunhozoon - 사람이 사랑하면 안 돼요",
"The Black Skirts - 기다린 만큼 더",
"Car, the garden - 나무",
"Car, the garden - 밤새",
"HYUKOH - 월량대표아적심",
"Deli Spice - 챠우챠우",
"ALEPH - Fall in Love Again ",
"Meaningful Stone - 꿈속의 카메라 ",
"Stella Jang - Colors",
"Sunwoo Jung A - 도망가자",
"Sunwoo Jung A - 구애",
"Kim Kak Sung - 인연이란 비관으로 ",
"TEYUN - 망부석 ",
"Lundi Blues - 눈빛 ",
"Luli Lee - Dive",
"SE SO NEON - 새소년 ",
"Band Nah - 불빛",
"ADOY - Wonder",
"The Rose - California ",
"O.O.O - 눈이 마주쳤을 때",
"Land of PeacE - Hometown",
"cotoba - 로스",
"Sumsher - tokyo (Feat. 팔드로)",
"Naivesign - Sea On A Summer Night",
"Acourve - 하고 싶은 말",
"Acoustic Collabo - 그대와 나, 설레임",
"Acourve - 그게 뭐라고",
"40 - 듣는편지",
"Motte - 도망가지마",
"Acourve - 잡지 않았어",
"Sweden Laundry - 목소리",
"O.WHEN - 오늘",
"One More Chance - 널 생각해",
"Mad Clown, Stella Jang - No Question",
"Acoustic Collabo - 묘해 너와",
"Sweden Laundry - 우리가 있던 시간",
"Sunwoo Jung A - 고양이",
"Lee Seol Ah - 말을건다",
"Let’s! - 호피폴라",
"SURL - Like Feathers",
"MOVNING - 폼페이(Love is Forever)",
"Band Nah - 각자의 밤",
"Kiha & The Faces - 기상시간은 정해져 있다",
"Dasutt - 비둘기",
"The Poles - moon in water",
"ADOY - Don't Stop",
"THE ELECTRICEELS - 적도",
"Gong Joong Geu Neul - 계절 ",
"Bye Bye Badman - Monolove",
"LAYBRICKS - 새벽",
"Fantastic Drugstore - Before Sunrise",
"Lacuna - Cake",
"Kisnue - Cool Kids"]

indie_kpop_song_artist = [
"Imagination - DEAN, Miso",
"낙서 (Feat. 백예린) - punchnello",
"머리어깨무릎발 (Feat. 원슈타인) - Lee Hi",
"ㅎㅇ (Feat. 페노메코) - LEEBADA",
"X (Feat. LEE HI) - CODE KUNST",
"O (Feat. LEE HI) - CODE KUNST",
"헤픈 우연 - HEIZE",
"Rainy day (Feat. ASH ISLAND, Skinny Brown) - PATEKO",
"Trip (Feat. hannah) - Leellarmarz",
"여기저기거기 (Feat. 수퍼비) - BUMKEY",
"지나쳐 (Feat. DEAN) - Loco",
"Hula Hoops (ft. BEENZINO, HWASA) - DPR LIVE",
"호불호 (Feat. Giriboy) (Prod. by GRAY) - Woo",
"XI (Feat. LEE HI) - CODE KUNST",
"Party For The Night (Feat. Loco & LeeHi) - GRAY",
"안녕히 (Feat. GRAY) - HOODY",
"Aqua Man - Beenzino",
"Sunshine (Feat. Crush) - HOODY",
"OUT OF CONTROL - DPR LIVE",
"Nike Shoes (Feat. Dynamic Duo) - Beenzino",
"호구 (Prod.by Fisherman of wybh) (feat.BrotherSu) - Giriboy",
"Boogie On & On - Beenzino",
"Make Love (Feat. Zion.T) - GRAY",
"보트 - george",
"교통정리 (Feat. HEIZE) - Giriboy",
"비누 - BIBI",
"구원자 (Feat. B.I) - Lee Hi",
"못참아! (feat. Loco) - meenoi",
"Celebration - BewhY",
"Rainy day(Feat. ASH ISLAND, Skinny Brown) - PATEKO",
"우린 자정을 넘어 - Wilcox",
"OKAY - ASH ISLAND",
"비가와 - Vincent Blue",
"어쩌면 또 마지막이 될까봐(Feat. Ayul) - Dept",
"OSAKA(Feat. ZICO) - ELO",
"너의 이름이 - Rheehab",
"We(OUI) - Jeebanoff",
"사랑은 위대해! - CHOILB",
"도시생활 - GroovyRoom, Leellarmarz",
"스쳐지나가자 - Hash Swan",
"록시땅 - Han Yo Han",
"Maybe I - OuiOui",
"아퍼 (Feat. Kid Milli, Lil tachi, 김승민, NO_EL, C JAMM) - Giriboy",
"어디 (Feat. ZICO,DEAN) - Killagramz",
"지구멸망 (Feat. Kirin) - sokodomo",
"​BITION WAY - ASH ISLAND, Leellarmarz, ZENE THE ZILLA, The Quiett",
"​GO HIGH (Feat. Woo, CHANGMO, The Quiett) (Prod. CODE KUNST) - Lee Youngji",
"Break - Bennzino",
"ITX (Feat. CHANGMO) - ZENE THE ZILLA",
"​Party Monster (Feat. EK, Bola, Make A Movie) (Prod. Neal) - MBA",
"​zone (Feat. Holynn, 팔로알토 (Paloalto), 123) - Minit",
"​NOAH (Feat. 박재범, Hoody) - HAON",
"​HELLP - RYNO,MELOH",
"​Cheese & Wine - DPR LIVE",
"​담아 (Feat. 염따, pH_1) (Prod. BOYCOLD) - Kid Milli, Swings, Mad Clown",
"​그래 그냥 내게 바로 (Skip And Kiss) (Prod. GroovyRoom) - Sik_K",
"EVERYTHING (Feat. 창모, Coogie, ASH ISLAND & BIBI)) - Way Ched"]

for music in indie_kpop_song_artist:
    # artist, song = music.split("-")
    song, artist = music.split("-")
    title = song
    artist = artist
    print("{")
    print('    "artist": "{}",'.format(str(artist[1:])))
    print('    "title": "{}"'.format(str(title[:-1])))
    print("},")